sudo: required
services:
  - docker

before_install:
  - docker build -t javidaslan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true javidaslan/react-test npm test --  --coverage

after_success:
  - docker build -t javidaslan/multi-client ./client
  - docker build -t javidaslan/multi-nginx ./nginx
  - docker build -t javidaslan/multi-server ./server
  - docker build -t javidaslan/multi-worker ./worker

  # push to docker HUB
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push javidaslan/multi-client
  - docker push javidaslan/multi-nginx
  - docker push javidaslan/multi-server
  - docker push javidaslan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-582864530478
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY